const COUNTRIES = {
	LOAD: 'COUNTRIES_LOAD',
	LOAD_SUCCESS: 'COUNTRIES_LOAD_SUCCESS',
	LOAD_FAIL: 'COUNTRIES_LOAD_FAIL'
}

const USER = {
	REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    
    LOGOUT: 'USER_LOGOUT'
}

const GAME = {
    GAME_LOAD: 'GAME_LOAD',
    GAME_LOAD_SUCCESS: 'GAME_LOAD_SUCCESS'
}

export { COUNTRIES, USER, GAME }