const COUNTRIES = {
	LOAD: 'COUNTRIES_LOAD',
	LOAD_SUCCESS: 'COUNTRIES_LOAD_SUCCESS',
	LOAD_FAIL: 'COUNTRIES_LOAD_FAIL'
}

const USER = {
	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',
}

export { COUNTRIES, USER }